meta:
  title: "Brian Norlander"
  description: "Hi, I'm Brian Norlander. I'm an Application Engineer at Rakuten in Tokyo. When I'm not exploring Tokyo I like to read, workout, learn new technologies and drink tea."
  facebook_image: "/img/brian.png"
  twitter_image: "/img/brian.png"
  image: "/img/brian.png"
  google_analytics_id: "UA-119534242-1"
  domain: "briannorlander.com"
  root: "https://briannorlander.com"

name: "Brian Norlander"
markdown: redcarpt
permalink: "/:categories/:title/"

plugins:
  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /:collection/:title/
  travel:
    output: true
    permalink: /:collection/:title/
  writing:
    output: true
    permalink: /:collection/:title/
  lists:
    output: true
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      hero_style: normal
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      cta: Check it out
      related_posts: projects
  -
    scope:
      path: ""
      type: travel
    values:
      layout: trip
      hero_style: full_bleed
      related_posts: travel
  -
    scope:
      path: ""
      type: lists
    values:
      layout: blog_post
  -
    scope:
      path: ""
      type: writing
    values:
      layout: blog_post

exclude:
  - node_modules
  - Gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - LICENSE.md
  - docs