meta:
  title: "Brian Norlander"
  description: "I am an undergraduate student at the University of Minnesota studying computer science and will be graduating in December 2018. My primary area of interest is creating data mining and machine learning applications. I like web development too!"
  facebook_image: "/img/brian.png"
  twitter_image: "/img/brian.png"
  image: "/img/brian.png"
  google_analytics_id: "UA-119534242-1"
  #domain: "briannorlander.com"
  #root: "https://briannorlander.com"

name: "Brian Norlander"
markdown: redcarpt
permalink: "/:categories/:title/"

plugins:
  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /:collection/:title/
  travel:
    output: true
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      hero_style: normal
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      cta: Check it out
      related_posts: projects
  -
    scope:
      path: ""
      type: travel
    values:
      layout: trip
      hero_style: full_bleed

exclude:
  - node_modules
  - Gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - LICENSE.md